services:
  _defaults:
    autowire: true
    autoconfigure: true

  Divante\MagentoIntegrationBundle\Service\Product\ProductStatusService:
    public: true
  Divante\MagentoIntegrationBundle\Service\Product\ProductService:
    public: true

  Divante\MagentoIntegrationBundle\Service\Category\CategoryService:
    public: true

  Divante\MagentoIntegrationBundle\Service\Category\CategoryStatusService:
    public: true

  Divante\MagentoIntegrationBundle\Service\Asset\AssetStatusService:
    public: true
